/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paneles;

//import static mathebattles.Main.fv;
import BD.DB_methods;
import mathebattles.Archivos;
import static paneles.MFrame.cl;
import static paneles.MFrame.pl;


/**
 *
 * @author aitor
 */
public class MMenu extends javax.swing.JPanel {
    
    /**
     * Creates new form MMenu
     */
    public MMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TITULO = new javax.swing.JLabel();
        Boton_Jugar = new javax.swing.JButton();
        Boton_Pts = new javax.swing.JButton();
        Boton_Login = new javax.swing.JButton();
        Boton_Salir = new javax.swing.JButton();

        TITULO.setFont(new java.awt.Font("Noto Sans", 0, 48)); // NOI18N
        TITULO.setText("Menu");

        Boton_Jugar.setText("Jugar");
        Boton_Jugar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_JugarMouseClicked(evt);
            }
        });
        Boton_Jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_JugarActionPerformed(evt);
            }
        });

        Boton_Pts.setText("Puntuaciones");
        Boton_Pts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_PtsActionPerformed(evt);
            }
        });

        Boton_Login.setText("Log In");
        Boton_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_LoginActionPerformed(evt);
            }
        });

        Boton_Salir.setText("Salir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Boton_Pts, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Boton_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Boton_Jugar, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Boton_Salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(TITULO)))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(TITULO)
                .addGap(64, 64, 64)
                .addComponent(Boton_Jugar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Boton_Pts, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(Boton_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_JugarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_JugarMouseClicked
        // TODO add your handling code here:  
        //fv.setVisible(true);
    }//GEN-LAST:event_Boton_JugarMouseClicked

    private void Boton_JugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_JugarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_JugarActionPerformed

    private void Boton_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_LoginActionPerformed
        // TODO add your handling code here:
        cl.show(pl, "LogIn");
    }//GEN-LAST:event_Boton_LoginActionPerformed

    private void Boton_PtsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_PtsActionPerformed
        // TODO add your handling code here:
        cl.show(pl, "Score");
        DB_methods.mejoresScores();
        
        Puntuaciones.Tabla_Score.setText(Archivos.leerMejores());
    }//GEN-LAST:event_Boton_PtsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Jugar;
    private javax.swing.JButton Boton_Login;
    private javax.swing.JButton Boton_Pts;
    private javax.swing.JButton Boton_Salir;
    public static javax.swing.JLabel TITULO;
    // End of variables declaration//GEN-END:variables
}
